<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5zHiO8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5zHiO8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ5zHiO8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ5zHiO8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ5zHiO8\App_KernelDevDebugContainer([
    'container.build_hash' => 'J5zHiO8',
    'container.build_id' => '4334cb8a',
    'container.build_time' => 1664282569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5zHiO8');
