<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container82xsEaT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container82xsEaT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container82xsEaT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container82xsEaT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container82xsEaT\App_KernelDevDebugContainer([
    'container.build_hash' => '82xsEaT',
    'container.build_id' => 'ba984a31',
    'container.build_time' => 1664276031,
], __DIR__.\DIRECTORY_SEPARATOR.'Container82xsEaT');
