<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN34I0Zf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN34I0Zf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN34I0Zf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN34I0Zf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN34I0Zf\App_KernelDevDebugContainer([
    'container.build_hash' => 'N34I0Zf',
    'container.build_id' => '7aa903bc',
    'container.build_time' => 1664262878,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN34I0Zf');
